name: "🔖 Detailed Release Feedback"
description: "Structured form to collect comprehensive feedback and bug reports for release {{ release.tag_name }}."
title: "[Feedback][{{ release.tag_name }}] "
labels: ["feedback", "release"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for testing **{{ release.tag_name }}**!  
        Please provide as much detail as possible to help us improve.
  - type: input
    id: version
    attributes:
      label: Extension version & commit
      description: e.g. 0.1.0-beta.1 @ commit `abcdef123`
      placeholder: 0.1.0-beta.1 @ abcdef123
    validations:
      required: true
  - type: dropdown
    id: rating
    attributes:
      label: Overall rating (1–5)
      options:
        - 1
        - 2
        - 3
        - 4
        - 5
      description: 1 = очень плохо, 5 = отлично
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - blocker
        - major
        - minor
        - enhancement
      description: Как сильно это влияет на ваш рабочий процесс?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: Что вы ожидали увидеть?
    validations:
      required: false
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: Что произошло на самом деле?
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Подробно опишите шаги для воспроизведения
      placeholder: 1. Открыть …  
2. Ввести …  
3. Нажать …
    validations:
      required: false
  - type: input
    id: workaround
    attributes:
      label: Workaround (if any)
      description: Были ли временные решения?
      placeholder: Отключил X, затем Y…
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Logs & stack traces
      description: Вставьте текст логов или приложите файл
    validations:
      required: false
  - type: checkboxes
    id: attachments
    attributes:
      label: Attachments
      options:
        - label: I attached screenshots
        - label: I attached log files
    validations:
      required: false
  - type: textarea
    id: feedback
    attributes:
      label: Additional feedback
      description: Что работает хорошо? Что стоит улучшить?
    validations:
      required: true
  - type: checkboxes
    id: consent
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to follow the Code of Conduct
          required: true
