# .github/workflows/issue-on-release.yml
name: "📝 Create feedback issue on release"

on:
  release:
    types: [published]    # срабатывает на Publish release :contentReference[oaicite:7]{index=7}

permissions:
  contents: read         # читать MD-шаблон
  issues: write          # создавать Issue :contentReference[oaicite:8]{index=8}

jobs:
  create-feedback-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Render Markdown template to file
        id: render
        uses: chuhlomin/render-template@v1
        with:
          template: .github/ISSUE_TEMPLATE/release-feedback.md
          vars: |
            release:
              tag_name: ${{ github.event.release.tag_name }}
          result_path: rendered-feedback.md   # сохраняет отрендеренный MD 

      - name: Verify rendered file
        run: |
          echo "=== rendered-feedback.md ==="
          cat rendered-feedback.md

      - name: Create release feedback issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          content-filepath: rendered-feedback.md  # готовый Markdown
          title: "Feedback for ${{ format('{0}', github.event.release.tag_name) }}"  # Простой заголовок
          labels: feedback  # Только метка feedback
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
