name: "📝 Create feedback issue on release"

on:
  release:
    types: [published]

permissions:
  contents: read    # для чтения шаблонов
  issues: write     # для создания issue

jobs:
  create-feedback-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create release feedback issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          # путь к нашему шаблону (маршаллится как Markdown)
          issue-file: .github/ISSUE_TEMPLATE/release-feedback.yml
          title: "Feedback for ${{ github.event.release.tag_name }}"
          labels: feedback, release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
