# .github/workflows/issue-on-release.yml
name: "📝 Create feedback issue on release"

on:
  release:
    types: [published]    # срабатывает на Publish release :contentReference[oaicite:2]{index=2}

permissions:
  contents: read         # для чтения шаблона
  issues: write          # для создания issue 

jobs:
  create-feedback-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Render feedback template to file
        id: render
        uses: chuhlomin/render-template@v1
        with:
          template: .github/ISSUE_TEMPLATE/release-feedback.yml
          vars: |
            release:
              tag_name: ${{ github.event.release.tag_name }}
          result_path: release-feedback.md   # ← автоматически создаст файл :contentReference[oaicite:3]{index=3}

      - name: Verify rendered file
        run: |
          echo "=== release-feedback.md ==="
          cat release-feedback.md

      - name: Create release feedback issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          content-filepath: release-feedback.md
          title: "[Feedback][${{ github.event.release.tag_name }}]"
          labels: feedback,release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
