# .github/workflows/issue-on-release.yml
name: "📝 Create feedback issue on release"

on:
  release:
    types: [published]    # срабатывает на Publish release :contentReference[oaicite:5]{index=5}

permissions:
  contents: read         # чтобы читать шаблон
  issues: write          # чтобы создавать Issue :contentReference[oaicite:6]{index=6}

jobs:
  create-feedback-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Render feedback template
        id: render
        uses: chuhlomin/render-template@v1
        with:
          template: .github/ISSUE_TEMPLATE/release-feedback.yml
          vars: |
            release:
              tag_name: ${{ github.event.release.tag_name }}

      - name: Create release feedback issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          content-filepath: release-feedback.md   # используем content-filepath, не issue-file :contentReference[oaicite:7]{index=7}
          title: "[Feedback][${{ github.event.release.tag_name }}]"
          labels: feedback,release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
