# .github/workflows/release-notify.yml
name: Notify Discord on Release

on:
  release:
    types: [published]    # только новые релизы

jobs:
  discord_notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send release to Discord
        uses: SethCohen/github-releases-to-discord@v1.16.2
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}  # <–– без "/github"
          username:   'ReleaseBot'
          avatar_url: 'https://i.imgur.com/AfFp7pu.png'
