# .github/workflows/release-notify.yml  
name: Notify Discord on Release              # название workflow (любой текст) :contentReference[oaicite:1]{index=1}

on:
  release:
    types: [published]                       # реагируем только на новые (published) релизы 

jobs:
  discord_notify:
    runs-on: ubuntu-latest                   # среда выполнения

    steps:
      - name: Send release to Discord
        uses: SethCohen/github-releases-to-discord@v1.16.2  # Action‑версия :contentReference[oaicite:3]{index=3}
        with:
          # Здесь — именно литерал expression, указывающий на secret!
          webhook_url: ${{ secrets.WEBHOOK_URL }}           # ← правильная ссылка на secret :contentReference[oaicite:4]{index=4}
          username:   'ReleaseBot'                         # опционально: имя бота в сообщении :contentReference[oaicite:5]{index=5}
          avatar_url: 'https://i.imgur.com/AfFp7pu.png'     # опционально: аватар бота :contentReference[oaicite:6]{index=6}
